#+TITLE: NIF Parcellation Schemes
#+AUTHOR: Tom Gillespie
#+DATE: ongoing
#+MACRO: semantic-l semantic label
#+MACRO: semantic-r semantic region
#+MACRO: parc-l parcellation label

#+MACRO: point point
#+MACRO: line line
#+MACRO: surface surface
#+MACRO: volume-conn spatial volume
#+MACRO: volume-conn-bounded bounded connected spatial volume
#+MACRO: volume-conn-bounded-prob probabilistically bounded connected spatial volume
#+MACRO: volume-conn-unbounded unbounded connected spatial volume

#+MACRO: semantic-r-spatial-surface semantic landmark region
#+MACRO: semantic-r-spatial semantic spatial region
#+MACRO: semantic-r-spatial-volume semantic spatial region
#+MACRO: semantic-r-spatial-volume-bounded semantic spatial region
#+MACRO: semantic-r-spatial-volume-unbounded semantic landmark region

#+MACRO: parc-r-surface parcellation landmark region
#+MACRO: parc-r-volume parcellation region
#+MACRO: parc-r-volume-bounded parcellation region
#+MACRO: parc-r-volume-bounded-prob probabilistic parcellation region
#+MACRO: parc-r-volume-unbounded parcellation landmark region

#+OPTIONS: num:nil html-preamble:t H:2

* A model for semantic anatomical regions and parcellation anatomical regions
  This file is a work in progress. \\
  The terminology used in this file is not final.

  It documents the logical basis for the NIFSTD parcellation schemes
  and their mappings to a variety of semantic anatomical schemes,
  [[https://uberon.org][Uberon]] being the most relevant.

  Please see [[https://github.com/SciCrunch/NIF-Ontology/issues/49]] for history and current developments.

  The files that are involved
  - [[https://github.com/SciCrunch/NIF-Ontology/blob/parcellation/ttl/generated/parcellation-artifacts.ttl][parcellation-artifacts.ttl]]
    catalogs the information artifacts from which the ontology files are derived
    and defines high level conceptual structure for the parts of a parcellation scheme
  - [[https://github.com/SciCrunch/NIF-Ontology/blob/parcellation/ttl/generated/parcellation-core.ttl][parcellation-core.ttl]]
    holds the object properties used to link the various parts of parcellations schemes together
  - [[https://github.com/SciCrunch/NIF-Ontology/blob/parcellation/ttl/bridge/parcellation-bridge.ttl][parcellation-bridge.ttl]]
    manages the import of all the files into the ontology
  - [[https://github.com/SciCrunch/NIF-Ontology/tree/parcellation/ttl/generated/parcellation/][parcellation/*]]
    holds the ontology files that actually represent the parcellation schemes.
  
* Spatial definitions
** Preamble
   | symbol | name                  |
   |--------+-----------------------|
   | ~*~    | named                 |
   | ~?~    | unnamed               |
   | ~--~   | unbounded (open)      |
   | ~__~   | bounded (closed)      |
   | ~O~    | connected             |
   | ~OO~   | disconnected          |
   | ~?>~   | part of not specified |
   | ~>~    | part of               |
   | ~/>~   | not part of           |
   | ~]?[~  | border not specified  |
   | ~I~    | borders               |
   | ~][~   | does not border       |

** thoughts
   There are three key relationships that we need to care about for brain regaions when annotating data.
   One: inside of. Two: close to. Three: part of. Specifically in this case cells or their processes.
   The full combination of these three produces the following. (Note that part of and inside of should be equivalent.)
   | inside of |
   | part of   |
   | close to  |
   A point (soma) can be close to something that is named by a parcellation label or
   inside of something that is named by a parcellation label.
   Another volume can be next to (bounded by)
   inside of something that is named by a parcellation label

   A parcellation with bounded regions and labels that are points inside or on the
   boundary of those regions has the following classes of labels. Each class tells
   you what you can infer about a neuron with a phenotype associated with that label.
   1. The only named point inside a bounded volume.  (I really like the term closed, but I think that its use is incorrect.)
   2. If the boundaries are closed then I don't care about the borders relationship because it can be computed from the atlas itself.

   The first level of parcellation is of the regions, named, or unnamed that are closed and bounded. If these
   regions are unnamed, then we need to do something about that. Sometimes, they may only be able to be defined
   as the complement of all named regions in a section. But, because the section is real and is bounded and
   closed we know that this is possible (thanks math!).
   
   A second issue that needs to be considered is when the same name is applied to a set of disconnected bounded regions.
   This could be where the idea of closed vs open comes into play. If there is another region that can have the same name
   then we might call any one so-named region as open, but it is not clear that this makes sense mathematically.
   The relevant definition is that $\exists$ at least two regions $A$ and $B$ bearing the same name such that $A \cap B = \emptyset$.
   These regions do not have a simple mapping to the {{{semantic-r-spatial-volume}}} listed below, but require more a more complex model.
   This is because the agreement needed as the basis for a definition may be significantly harder to obtain due to the number
   of points that are required for agreement. An example of this is the rodent internal capsule where fiber tracts are interspersed
   and do not form a single contiguous structure as they do in human.

** tables

   #+NAME: table:spatial
   #+CAPTION: Spatial definitions
   | Name source         | Anatomical Entities                    | Spatially defined by                                                                                                                              | Examples                                     |
   |---------------------+----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------|
   | {{{semantic-l}}}    | {{{semantic-r}}}                       |                                                                                                                                                   | Uberon, BrainInfo, Swanson                   |
   | {{{semantic-l}}}    | {{{semantic-r-spatial-volume}}} [fn:0] | A point or {{{volume-conn-unbounded}}} that contains that point                                                                                   |                                              |
   | {{{parc-l}}} [fn:1] | {{{parc-r-volume-bounded}}}            | A {{{volume-conn-bounded}}} [fn:2]                                                                                                                | Allen MBA CCFv3                              |
   | {{{parc-l}}}        | {{{parc-r-volume-unbounded}}} [fn:3]   | An {{{volume-conn-unbounded}}} defined by point or a line and a point on that line or a subset of a surface and a line or a point on that surface |                                              |
   | {{{parc-l}}}        | {{{parc-r-volume-bounded-prob}}}       | A {{{volume-conn-bounded-prob}}}                                                                                                                  | Jülich histological, Harvard-Oxford cortical |

   [[file:images/parcellation-visual.svg]]

   #+NAME: table:mapping-1
   #+CAPTION: Mapping between parcellation and semantic labels
   | Not a spatial source | Spatial source |
   |----------------------+----------------|
   | {{{semantic-l}}}     | {{{parc-l}}}   |

   #+NAME: table:mapping-2
   #+CAPTION: Mapping between parcellation and spatial semantic regions
   | Point representation             | Spatial representation |
   |----------------------------------+------------------------|
   | {{{semantic-r-spatial-volume}}}  | {{{parc-r-volume}}}    |
   | {{{semantic-r-spatial-surface}}} | {{{parc-r-surface}}}   |

   + a point representation *isDelineatedBy* a spatial representation
   + a spatial representation *delineates* a point representation

[fn:0] Because these are defined by a single point they technically encompass landmarks
and a variety of other immaterial anatomical entities as well. In some cases the point
could be defined as being confined to a surface. Modelling of surfaces is fairly good
in uberon
[fn:1] Futher consideration is needed about whether parcellation labels are distinct from
semantic labels. The example to considers is what happens when someone creates and atlas
and uses the uberon identifiers as atlas labels directly. Does that break the semantics
and if so how? The answer is yes. The source of the definition does matter and if we
artifically extend their semantics to cover other atlases or conecepts or regions outside
the source's original use then that is a problem. See [[https://github.com/SciCrunch/NIF-Ontology/issues/49#issuecomment-349395453]]
for reference.
[fn:2] As long as the 3d volume is topoligically equivalent to a sphere, unconnected regions
in planes of section are fine.
[fn:3] Landmark is provisional and probably needs to be changed. These cover things like fissures
or other features that do not form closed spatial volumes and tend to dissapear under a variety
of topological transformations.

* Conceptual model for artifacts, labels, and regions
   [[file:images/parcellation-overview.svg]]
* Parcellation region scope
   Parcellation labels only apply to all regions that could
   potentially be registerd to an atlas that uses those labels. [fn:-0]
   
   Note that this implies that an atlast artifact must actually
   exist and be able to be used to register data.

   The only entities that are in scope for use for a set of parcellation labels
   are those that could have been, were, are, or could be registered using some
   spatial source that uses those parcellation lables to uniquely identify
   spatially distinct anatomical entities.

[fn:-0] Wording not final. Parcellation regions are only in scope for entities...?
* Universality
  In order to clarify the effects of attaching semantic and parcellation labels onto
  spatial regions we introduce the idea of universality of a concept.

  A concept is universal [fn:-3] up to an agreement-group under a relationship if it is possible
  to find some other-concept such that there is a group of people who all mutually agree
  about the existence of the other-concept all of whom that use the concept also agree
  that the relationship holds between it and the other-concept.
  
  Alternately, if you can find anything that a group can agree about and some relationship,
  then any additional concept that is used by a subset of that group is universal under that
  relationship for the whole group if everyone in that subset agrees about the relationship
  between the additional concept and the thing the whole group agrees about.
  
  For example, it is probably fair to say that 'thalamus' is universal under partonomy
  up to the group of all people who agree about what a brain is. For any group of people
  who know and agree about what a brain is and that also know what a thalamus is they
  will agree that a thalamus is part of a brain.
  
  Note that in this ven diagram we are actually seening a case 
  This ven diagram helps clarify one instance of 
  if the 'People who also agree that thalamus is part of brain'

  Universality is a more general way of expressing that it is possible to find common ground.
  Everyone does not have to agree about whether the thalamus is part of the forbrain or the
  midbrain for the concept to be universal under partonomy, since they all agree that it is
  indeed part of the brain.
  
  Universality does not mean that a term is correct or true, only that it is used consistently
  within a specific group.

  Universality is useful for identifying terminology that is not consistent.
  If there is someone in an agreement group for the spinal cord, but they disagree
  about whether a dorsal root gangion is part of the spinal cord (avoiding circular
  definitions that define it as such) then the dorsal root ganglion is not universal
  under partonomy for that agreement group about the spinal cord.
  
  To give the example that inspired this. If someone uses an Allen Mouse Brain Atlas label
  to refer to a rat brain region the, term (or perhaps that useage) is not universal under
  partonomy. Despite mutual agreement about what a mouse brain is and a rat brain
  is, I do not agree that something that names part of a mouse brain can name something
  that is part of a rat brain. This would also be true for rodent brains and brains generally.
  
[fn:-3] This should probably be 'minimally universal'. Maximally universal under a
realationship would be finding that the set of concept other-concept pairs for the
concept in question were the same for all members of the agreement group.

** Semantic region [fn:4]
   #+BEGIN_SRC racket
   given all people
   an agreement-group about 'thing
   is any member of {subset-of-people in (powerset people) | (mutually-agree? subset-of-people '(exists? 'thing))}
   a 'semantic-region is-said-to-be universal up to an agreement-group iff
   there-exists some 'other-region such-that
   for members of an agreement-group about 'other-region
   {person in members | (uses-term-for? person 'semantic-region)}  ; universal agreement group
   is identical to
   {person in members | (agrees? p '(part-of? 'semantic-region 'other-region))}
   ; the set of members that agrees that 'semantic-region is part-of other-region
   #+END_SRC
   In english.
   A semantic anatomical region is said to be universal up to an agreement group
   if and only if it is possible to find some other region such that all of the
   people who agree about the definition of that other region also agree that
   the region in question is part of that other region.

[fn:4] We need a way to deal with the immaterial anatomical entities from uberon

** Semantic spatial region
   #+BEGIN_SRC racket
   a 'semantic-spatial-region is universal iff
   it is a 'semantic-region that is universal up to an agreement-group and
   there-exists some 'point in space such-that
   for-all 'person in the agreement-group that also use the term  ; universal-agreement-group maybe?
   (agrees? 'person '(contained-in? 'semantic-spatial-region 'point))
   #+END_SRC
   In english.
   A semantic spatial region is universal if and only iff it is a universal semantic
   region and all the people in the universal agreement group can agree on at least
   one real spatial location (point) that they all agree is contained in the region
   in question.

** Parcellation region (and probabilistic parcellation regions)
   Universality is derived from the spatial structure of the atlas and the species
   and developmental stage for which they are defined, as long as the subjects being
   registered meet those criteria.

   The full explication of the criteria need to support universality is more complex
   and includes quite a bit of provenance information about the processes used to
   determine whether the atlas is applicable for the subject in question.
   However, for the purposes of communication we don't need to dig further for now.
